version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authentication
    ports:
      - "8889:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

  servers:
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/authentication"
      JWT_SECRET: "your_jwt_secret"
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - servers

volumes:
  db_data:
