import { DM_Sans, Inter } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { theme } from '../theme/theme';
import "./globals.css";

const dmSans = DM_Sans({
  subsets:['latin'],
  variable:'--font-dmsans'
})

const inter = Inter({
  subsets:['latin'],
  variable:'--font-inter'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${inter.variable} antialiased`}
      >
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
