import HomeFooter from "@/components/homefooter/HomeFooter";
import { Navbar } from "@/components/navbar/Navbar";

export const metadata = {
  title: "AdminZ",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="mx-auto max-w-[1400px] px-5 min-h-screen flex flex-col">
      <Navbar />
      <div className="flex-grow flex items-center">{children}</div>
      <HomeFooter />
    </main>
  );
}
